# Generated by Django 3.2.6 on 2022-06-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20220615_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retweet',
            options={'ordering': ['usuario']},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['texto']},
        ),
        migrations.RemoveField(
            model_name='retweet',
            name='fechaRetweet',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='fecha',
        ),
    ]
